CREATE SEQUENCE  SEQ_BOARD;

CREATE TABLE TBL_BOARD(
   BOARD_NUMBER NUMBER,
   BOARD_TITLE VARCHAR2(1000),
   BOARD_WRITER VARCHAR2(1000),
   BOARD_CONTENT VARCHAR2(1000),
   BOARD_REGISTER_DATE DATE DEFAULT SYSDATE,
   BOARD_UPDATE_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NUMBER)   
);

SELECT * FROM TBL_BOARD;

INSERT INTO TBL_BOARD
(BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
VALUES(SEQ_BOARD.NEXTVAL, '테스트 제목', 'testA', '테스트 내용');

SELECT SYSDATE FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;
SELECT * FROM TBL_BOARD;

SELECT ROWNUM, BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE 
FROM
(
   SELECT /*+ INDEX_DESC(TBL_BOARD PK_BOARD)*/ BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE 
   FROM TBL_BOARD
);

SELECT BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE 
FROM
(
   /*최신순으로 정렬된 테이블에 ROWNUM 추가*/
   SELECT ROWNUM R, BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE 
   FROM
   (
      /*최신순으로 정렬*/
      SELECT BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT, BOARD_REGISTER_DATE, BOARD_UPDATE_DATE 
      FROM TBL_BOARD
      ORDER BY BOARD_NUMBER DESC
   )
   /*ROWNUM을 사용해서 마지막 게시글까지만 조회, ROWNUM은 무조건 1부터 시작하기 때문에 끝값만 끊어낼 수 있다.*/
   WHERE ROWNUM < 3
)
/*이미 결과테이블에서 ROWNUM을 붙였기 때문에 서브쿼리에 있는 ROWNUM인 R을 사용하여 시작 값을 처리할 수 있다.*/
WHERE R > 1;

INSERT INTO TBL_BOARD (BOARD_NUMBER, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT)
(SELECT SEQ_BOARD.NEXTVAL, BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT FROM TBL_BOARD);