CREATE SEQUENCE SEQ_FILE;

CREATE TABLE TBL_FILE(
	FILE_NUMBER NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
	FILE_NAME VARCHAR2(1000),
	FILE_UPLOAD_PATH VARCHAR2(1000),
	FILE_UUID VARCHAR2(500),
	FILE_SIZE NUMBER,
	FILE_IMAGE_CHECK CHAR(1),
	BOARD_NUMBER NUMBER,
	CONSTRAINT FK_FILE FOREIGN KEY(BOARD_NUMBER) REFERENCES TBL_BOARD(BOARD_NUMBER)
);

SELECT * FROM TBL_FILE;