CREATE SEQUENCE SEQ_ITEM;

CREATE TABLE TBL_ITEM(
	ITEM_NUMBER NUMBER CONSTRAINT PK_ITEM PRIMARY KEY,
	ITEM_NAME VARCHAR2(500),
	ITEM_PRICE NUMBER,
	ITEM_STOCK NUMBER DEFAULT 0
);

SELECT * FROM TBL_ITEM;

INSERT INTO TBL_ITEM (ITEM_NUMBER, ITEM_NAME, ITEM_PRICE, ITEM_STOCK)
VALUES(SEQ_ITEM.NEXTVAL, '감자', 2000, 90);

INSERT INTO TBL_ITEM (ITEM_NUMBER, ITEM_NAME, ITEM_PRICE, ITEM_STOCK)
VALUES(SEQ_ITEM.NEXTVAL, '고구마', 3000, 50);

INSERT INTO TBL_ITEM (ITEM_NUMBER, ITEM_NAME, ITEM_PRICE, ITEM_STOCK)
VALUES(SEQ_ITEM.NEXTVAL, '당근', 1500, 75);

INSERT INTO TBL_ITEM(ITEM_NUMBER, ITEM_NAME, ITEM_PRICE, ITEM_STOCK)
(SELECT SEQ_ITEM.NEXTVAL, ITEM_NAME, ITEM_PRICE, ITEM_STOCK FROM TBL_ITEM);

TRUNCATE TABLE TBL_ITEM;