CREATE TABLE TBL_ORDER(
   ORDER_ID VARCHAR2(500),
   ORDER_DATE DATE DEFAULT CURRENT_DATE,
   ITEM_NUMBER NUMBER,
   ITEM_COUNT NUMBER,
   ORDER_PRICE NUMBER,
   CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_ID, ITEM_NUMBER),
   CONSTRAINT FK_ORDER FOREIGN KEY(ITEM_NUMBER) REFERENCES TBL_ITEM(ITEM_NUMBER)
);


SELECT * FROM TBL_ORDER;   

/*매일 1개씩 INSERT*/

CREATE TABLE TBL_ORDER_SEQ(
   ORDER_SEQ NUMBER DEFAULT 0,
   ORDER_DATE DATE
);

SELECT * FROM TBL_ORDER_SEQ;

/*결제 시 주문번호 1 증가*/
UPDATE TBL_ORDER_SEQ
SET ORDER_SEQ = ORDER_SEQ + 1;

/*주문번호 조회*/
SELECT TO_CHAR(CURRENT_DATE, 'yyyymmdd') || ORDER_SEQ ORDER_NUMBER FROM
(
   SELECT ORDER_SEQ, ORDER_DATE FROM TBL_ORDER_SEQ ORDER BY ROWNUM DESC
)
WHERE ROWNUM = 1;

/*매일 12시마다 추가*/
INSERT INTO TBL_ORDER_SEQ(ORDER_DATE)
VALUES(CURRENT_DATE);

TRUNCATE TABLE TBL_ORDER_SEQ;
TRUNCATE TABLE TBL_ORDER;
DROP TABLE TBL_ORDER;


INSERT INTO TBL_ORDER_SEQ(ORDER_DATE)
VALUES(CURRENT_DATE);

SELECT * FROM TBL_ORDER;











