CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
   REPLY_NUMBER NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(1000),
   REPLY_WRITER VARCHAR2(1000),
   REPLY_REGISTER_DATE DATE DEFAULT CURRENT_DATE,
   REPLY_UPDATE_DATE DATE DEFAULT CURRENT_DATE,
   BOARD_NUMBER NUMBER,
   CONSTRAINT FK_REPLY FOREIGN KEY(BOARD_NUMBER) REFERENCES TBL_BOARD(BOARD_NUMBER)
   ON DELETE CASCADE
);

SELECT * FROM TBL_REPLY;

DELETE FROM TBL_REPLY WHERE REPLY_WRITER = '황지수';