CREATE SEQUENCE SEQ_FISH;

CREATE TABLE TBL_FISH(
	FISH_NUMBER NUMBER PRIMARY KEY,
	FISH_NAME VARCHAR2(100) unique,
	FISH_COUNT NUMBER
);

DROP TABLE TBL_FISH;

INSERT INTO TBL_FISH(FISH_NUMBER,FISH_NAME,FISH_COUNT)
VALUES (SEQ_FISH.NEXTVAL,'배스','5');

SELECT * FROM TBL_FISH;