/*회원*/
/*
 * 회원번호
 * 아이디
 * 이름
 * 비밀번호
 * 전화번호
 * 닉네임
 * 이메일
 * 주소
 * 생년월일
 * 성별
 * 추천인 아이디
 * 직업
 * 
 * */
CREATE SEQUENCE SEQ_USER;

CREATE TABLE TBL_USER(
   USER_NUMBER NUMBER CONSTRAINT PK_USER PRIMARY KEY,
    USER_ID VARCHAR2(1000) UNIQUE NOT NULL,
    USER_NAME VARCHAR2(1000) NOT NULL,
    USER_PASSWORD VARCHAR2(1000) NOT NULL,
    USER_PHONE VARCHAR2(1000) UNIQUE NOT NULL,
    USER_NICKNAME VARCHAR2(1000) NOT NULL,
    USER_EMAIL VARCHAR2(1000) UNIQUE NOT NULL,
    USER_ADDRESS VARCHAR2(1000),
    USER_BIRTH_DATE DATE,
    USER_GENDER VARCHAR2(100) DEFAULT 'N' CONSTRAINT BAN_GENDER CHECK(USER_GENDER IN('M', 'W', 'N')),
    USER_RECOMMENDER_ID VARCHAR2(1000),
    USER_JOB VARCHAR2(1000)
);

ALTER TABLE TBL_USER RENAME COLUMN USER_RECOMMANDER_ID TO USER_RECOMMENDER_ID;

SELECT * FROM TBL_USER;

INSERT INTO TBL_USER
(USER_NUMBER, USER_ID, USER_NAME, USER_PASSWORD, USER_PHONE, USER_NICKNAME, USER_EMAIL, USER_ADDRESS, USER_BIRTH_DATE, USER_RECOMMENDER_ID, USER_JOB)
VALUES(SEQ_USER.NEXTVAL, 'jbg', '장보고', '5555', '01077778888', 'zl존장보고333', '장보고@gmail.com', '경기도 남양주시', '2003-12-04', 'hds', '교육');

SELECT * FROM TBL_USER
WHERE USER_ID = 
(
   SELECT USER_RECOMMENDER_ID FROM TBL_USER
   WHERE USER_ID = 'hgd'
);



