
SELECT * FROM TBL_ANIMAL;
SELECT * FROM TBL_FISH;

SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_REPLY;

SELECT * FROM TBL_MACHINE;
SELECT * FROM TBL_FAN;
SELECT * FROM TBL_WASHING_MACHINE;

SELECT * FROM TBL_TEACHER;
SELECT * FROM TBL_STUDENT;

SELECT * FROM TBL_PEOPLE;
SELECT * FROM TBL_USER;



SELECT *  FROM TBL_MONEY,TBL_PEOPLE WHERE USER_ID = 103;
SELECT SUM(MONEY_CASH)  FROM TBL_MONEY,TBL_PEOPLE WHERE USER_ID = 103;
SELECT SUM(MONEY_CASH)  FROM TBL_MONEY,TBL_PEOPLE;
SELECT SUM(MONEY_CASH)  FROM TBL_MONEY;

TRUNCATE TABLE TBL_SERVICE;

SELECT * FROM TBL_DONATION;
SELECT DONATION_TYPE, DONATION_ID, CREATED_DATE, UPDATED_DATE, PEOPLE_USER_ID, SCHOOL_USER_ID
FROM TBL_DONATION;

DROP TABLE TBL_FILE;
DROP TABLE TBL_REPLY;

DELETE FROM TBL_USER
WHERE USER_ID=3;

DELETE FROM TBL_PEOPLE
WHERE USER_ID=3;

TRUNCATE TABLE TBL_FILE;
TRUNCATE TABLE TBL_USER;
TRUNCATE TABLE TBL_SCHOOL;
TRUNCATE TABLE TBL_ALARM;

DELETE FROM TBL_USER U
WHERE USER_PASSWORD = 12341234;



DELETE FROM TBL_FILE
WHERE FILEID=14;




